---
- name: ECK Operator installation
  hosts: all
  become: yes  
  gather_facts: false
- name: Importing the openshift login playbook
  import_playbook: ../openshift/openshift_login.yml
  tasks: 
    - name: Create a k8s namespace
      k8s:
        name: openshift-operators
        api_key: "{{ openshift_token }}"
        api_version: v1
        kind: Namespace
        state: present
        validate_certs: no

    - name: ECK Operator Installation based on the Subscription definition
      k8s:
        definition: 
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: elasticsearch-eck-operator-certified
            namespace: openshift-operators
          spec:
            channel: stable
            installPlanApproval: Automatic
            name: elasticsearch-eck-operator-certified
            source: certified-operators
            sourceNamespace: openshift-marketplace
            startingCSV: elasticsearch-eck-operator-certified.v2.6.2

    - name: Create New Elasticsearch instance 
      k8s:
        definition:
          apiVersion: elasticsearch.k8s.elastic.co/v1
          kind: Elasticsearch
          metadata:
            name: elasticsearch-sample
            namespace: openshift-operators
          spec:
            auth: {}
            http:
              service:
                metadata: {}
                spec: {}
              tls:
                certificate: {}
            monitoring:
              logs: {}
              metrics: {}
            nodeSets:
              - config:
                  node.attr.attr_name: attr_value
                  node.roles:
                    - master
                    - data
                  node.store.allow_mmap: false
                count: 1
                name: default
                podTemplate:
                  metadata:
                    creationTimestamp: null
                    labels:
                      foo: bar
                  spec:
                    containers:
                      - name: elasticsearch
                        resources:
                          limits:
                            cpu: '2'
                            memory: 4Gi
                          requests:
                            cpu: '1'
                            memory: 4Gi
            transport:
              service:
                metadata: {}
                spec: {}
              tls:
                certificate: {}
            updateStrategy:
              changeBudget: {}
            version: 8.6.0  

    - name: Create New Kibana instance 
      k8s:
        definition:
          apiVersion: kibana.k8s.elastic.co/v1
          kind: Kibana
          metadata:  
            name: kibana-sample
            namespace: openshift-operators  
          spec:
            count: 1
            elasticsearchRef:
              name: elasticsearch-sample
            enterpriseSearchRef: {}
            http:
              service:
                metadata: {}
                spec: {}
              tls:
                certificate: {}
            monitoring:
              logs: {}
              metrics: {}
            podTemplate:
              metadata:
                creationTimestamp: null
                labels:
                  foo: bar
              spec:
                containers:
                  - name: kibana
                    resources:
                      limits:
                        cpu: '2'
                        memory: 2Gi
                      requests:
                        cpu: 500m
                        memory: 1Gi
            version: 8.6.0

