---
- name: ECK Operator installation
  hosts: leafs
  gather_facts: false
  module_defaults:
    group/k8s:
      host: https://api.ocp-by-awx.cp.fyre.ibm.com:6443
      
  tasks: 

  # Authenticate to remote cluster

  

    - name: Log in to OC 
      k8s_auth:
        username: kubeadmin
        password: z2NVC-GkVFr-SNgUI-hf9La
        validate_certs: no
      register: k8s_auth_results



# Creating the Namespace in remote cluster

    - name: Create a k8s namespace
      k8s:
        name: openshift-operators # defining the namespace
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        api_version: v1
        kind: Namespace
        state: present    # State=present when you need to create new
        validate_certs: no


# ECK Operator installation based on Subscription definition

    - name: ECK Operator Installation based on the Subscription definition
      k8s:
        definition: 
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: elasticsearch-eck-operator-certified
            namespace: openshift-operators
          spec:
            channel: stable
            installPlanApproval: Automatic
            name: elasticsearch-eck-operator-certified
            source: certified-operators
            sourceNamespace: openshift-marketplace
            startingCSV: elasticsearch-eck-operator-certified.v2.6.2

# Create Elasticsearch instance 

    - name: Create New Elasticsearch instance 
      k8s:
        definition:
          apiVersion: elasticsearch.k8s.elastic.co/v1
          kind: Elasticsearch
          metadata:
            name: elasticsearch-sample-test4
            namespace: openshift-operators
          spec:
            auth: {}
            http:
              service:
                metadata: {}
                spec: {}
              tls:
                certificate: {}
            monitoring:
              logs: {}
              metrics: {}
            nodeSets:
              - config:
                  node.attr.attr_name: attr_value
                  node.roles:
                    - master
                    - data
                  node.store.allow_mmap: false
                count: 3
                name: default
                podTemplate:
                  metadata:
                    creationTimestamp: null
                    labels:
                      foo: bar
                  spec:
                    containers:
                      - name: elasticsearch
                        resources:
                          limits:
                            cpu: '2'
                            memory: 4Gi
                          requests:
                            cpu: '1'
                            memory: 4Gi
            transport:
              service:
                metadata: {}
                spec: {}
              tls:
                certificate: {}
            updateStrategy:
              changeBudget: {}
            version: 8.6.0  

# Create Kibana instance 

    - name: Create New Kibana instance 
      k8s:
        definition:
          apiVersion: kibana.k8s.elastic.co/v1
          kind: Kibana
          metadata:  
            name: kibana-sample-test4
            namespace: openshift-operators  
          spec:
            count: 1
            elasticsearchRef:
              name: elasticsearch-sample-test4
            enterpriseSearchRef: {}
            http:
              service:
                metadata: {}
                spec: {}
              tls:
                certificate: {}
            monitoring:
              logs: {}
              metrics: {}
            podTemplate:
              metadata:
                creationTimestamp: null
                labels:
                  foo: bar
              spec:
                containers:
                  - name: kibana
                    resources:
                      limits:
                        cpu: '2'
                        memory: 2Gi
                      requests:
                        cpu: 500m
                        memory: 1Gi
            version: 8.6.0