---
- name: k8s-operations
  hosts: all
  become: yes
  # vars:
  #   ansible_python_interpreter: /usr/bin/python2.7
  gather_facts: false
  tasks:
    - name: Download oc CLI
      shell: curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.6/linux/oc.tar.gz
    - name: Extract oc CLI
      shell: tar -xf oc.tar.gz -C /usr/local/bin/
    - name: Set executable permission
      shell: chmod +x /usr/local/bin/oc
    # - name: Verify installation
    #   shell: oc version
    - name: Login to openshift cluster
      shell: oc login -u kubeadmin -p CExEF-C82mb-E3BtR-QaEmh https://api.test2-10022023.cp.fyre.ibm.com:6443
      register: login_output
    - name: Get openshift cluster token
      shell: oc whoami -t
      register: token_output
      when: login_output.rc == 0
    - name: Set openshift cluster token as variable
      set_fact:
        openshift_token: "{{ token_output.stdout }}"
      when: token_output.rc == 0
    - name: Create a k8s namespace
      k8s:
        name: testing
        api_key: "{{ openshift_token }}"
        api_version: v1
        kind: Namespace
        state: present
        validate_certs: no